name: Pipeline CI/CD
on: 
  push:
    branches:
        - main
  workflow_dispatch: 
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
      - uses: actions/checkout@v4

      - name: Instalação do Node
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Instalação das dependências
      - run: npm install 

      - name: Rodar o build
      - run: npm run build
        env:
            TMDB_API_URL: ${{ vars.TMDB_API_URL }}
            TMDB_API_KEY: ${{secrets.TMDB_API_KEY}}
            NEXT_PUBLIC_TMDB_API_IMG_URL: ${{vars.NEXT_PUBLIC_TMDB_API_IMG_URL}}
